openapi: 3.0.1
info:
  title: OAuthTokenProvider
  description: | 
    The token management API for client credential flow (2-Legged Oauth). There are 2 ways to call the token:
    * With authorization header (base64 encoded credential) + query strings.
    * With request body.
  contact:
    name: API Support
    email: apidir-contact@umich.edu
  version: v1
servers:
  - url: https://gw-test.api.it.umich.edu/um/oauth2
security:
  - basicAuth: []
paths:
  /token:
    post:
      summary: Operation to generate access token, supports oauth client_credentials grant type.
      operationId: Token
      parameters:
        - name: scope
          in: query
          description: scopes provide a way to limit the amount of access that is granted to an access token
          required: true
          schema:
            type: string
        - name: grant_type
          in: query
          description: OAuth grant, currently only supports client_credentials
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                scope:
                  type: string
                  description: scopes provide a way to limit the amount of access that is granted to an access token
                grant_type:
                  type: string
                  description: OAuth grant, currently only supports client_credentials
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Bad Request - The input model is invalid or malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '401':
          description: Unauthorized - Token is expired or Client Id or subscription are invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: Internal Server Error - Undocumented error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '503':
          description: Service Unavailable - The service is temporarily unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
components:
  schemas:
    ApiErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string
    TokenResponse:
      type: object
      properties:
        token_type:
          type: string
        access_token:
          type: string
        expires_in:
          type: string
        scope:
          type: string
        client_id:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      description: The value of username should be your application client_id and password should be client_secret.
      scheme: basic